file_format: "1"
id: raven
name: The Raven 
type: shield
url: https://github.com/EmileVezinaCoulombe/zmk-config-raven
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - raven_left
  - raven_right
