file_format: "1"
id: raven
name: Flying Raven 
type: shield
url: https://github.com/EmileVezinaCoulombe/zmk-config-raven
requires: [pro_micro]
features:
  - keys
siblings:
  - raven_left
  - raven_right
