# This file generates the GitHub Actions matrix
board:
  - nice_nano_v2
shield:
  - raven_left
  - raven_right
include:
  - board: nice_nano_v2
    shield: raven_left
  - board: nice_nano_v2
    shield: raven_right
  - board: nice_nano_v2
    shield: settings_reset
