manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: EmileVezinaCoulombe
      url-base: https://github.com/EmileVezinaCoulombe
  projects: 
    - name: zmk
      remote: EmileVezinaCoulombe
      revision: master
      import: app/west.yml
  self:
    path: config
